/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket_billing_system;
import java.sql.Connection;
//import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Product_list extends javax.swing.JFrame {
    
    /**
     * Creates new form Product_list2
     */
    String selectedItem = "none";
    
    public void updateList(){
        Connection con = DBConnection.connect();
        
        try{
            DefaultTableModel table = (DefaultTableModel) product_list_table.getModel();
            String sql = "select * from product_list;";
            Statement st = con.createStatement();
            
            table.setRowCount(0);
            ResultSet res = st.executeQuery(sql);

            while(res.next()){
                int ID = res.getInt("ID");
                String Name = res.getString("Name");
                String Type = res.getString("Type");
                int Price = res.getInt("Price");
                int Quantity = res.getInt("Quantity");

                Object[] newRow = {ID, Name, Type, Price, Quantity};
                table.addRow(newRow);
            }
            
            con.close();
            
        } catch (Exception a){
            System.out.println("Data not inserted, ERROR: "  + a);
        }
    }
    
    public Product_list() {
        initComponents();
        updateList();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        product_list_table = new javax.swing.JTable();
        create_new_product = new javax.swing.JButton();
        modify_product_button = new javax.swing.JButton();
        remove_button = new javax.swing.JButton();
        back_productlist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Product List");

        product_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        product_list_table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        product_list_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        product_list_table.setShowGrid(true);
        product_list_table.setSurrendersFocusOnKeystroke(true);
        product_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_list_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(product_list_table);
        if (product_list_table.getColumnModel().getColumnCount() > 0) {
            product_list_table.getColumnModel().getColumn(0).setMinWidth(50);
            product_list_table.getColumnModel().getColumn(0).setPreferredWidth(50);
            product_list_table.getColumnModel().getColumn(0).setMaxWidth(50);
            product_list_table.getColumnModel().getColumn(0).setHeaderValue("ID");
            product_list_table.getColumnModel().getColumn(1).setMinWidth(250);
            product_list_table.getColumnModel().getColumn(1).setPreferredWidth(250);
            product_list_table.getColumnModel().getColumn(1).setMaxWidth(250);
            product_list_table.getColumnModel().getColumn(1).setHeaderValue("Name");
            product_list_table.getColumnModel().getColumn(2).setMinWidth(100);
            product_list_table.getColumnModel().getColumn(2).setPreferredWidth(100);
            product_list_table.getColumnModel().getColumn(2).setMaxWidth(100);
            product_list_table.getColumnModel().getColumn(2).setHeaderValue("Type");
            product_list_table.getColumnModel().getColumn(3).setMinWidth(100);
            product_list_table.getColumnModel().getColumn(3).setPreferredWidth(100);
            product_list_table.getColumnModel().getColumn(3).setMaxWidth(100);
            product_list_table.getColumnModel().getColumn(3).setHeaderValue("Price");
            product_list_table.getColumnModel().getColumn(4).setMinWidth(100);
            product_list_table.getColumnModel().getColumn(4).setPreferredWidth(100);
            product_list_table.getColumnModel().getColumn(4).setMaxWidth(100);
            product_list_table.getColumnModel().getColumn(4).setHeaderValue("Quantity");
        }

        create_new_product.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        create_new_product.setText("Create new");
        create_new_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_new_productActionPerformed(evt);
            }
        });

        modify_product_button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modify_product_button.setText("Modify");
        modify_product_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modify_product_buttonActionPerformed(evt);
            }
        });

        remove_button.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        remove_button.setText("Remove");
        remove_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_buttonActionPerformed(evt);
            }
        });

        back_productlist.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        back_productlist.setActionCommand("Back");
        back_productlist.setLabel("Back");
        back_productlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_productlistActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(183, 183, 183)
                        .addComponent(back_productlist, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(create_new_product, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(modify_product_button, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(remove_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(back_productlist))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_new_product, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify_product_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void create_new_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_new_productActionPerformed
        Create_product newWindow = new Create_product(this, true);
        newWindow.setVisible(true);
        
        newWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                updateList(); //Ktu behet update databaza jon pasi kemi krijuar produktin e ri
                //Pra, therritet funksioni updateList() kur mbyllet dritarja Create_product.
            }
        });
    }//GEN-LAST:event_create_new_productActionPerformed

    private void modify_product_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modify_product_buttonActionPerformed
        if(product_list_table.getSelectedRow() != -1 && !"none".equals(selectedItem)){
            Modify_product modifyWindow = new Modify_product(this, true, product_list_table.getSelectedRow()+1,selectedItem);
            modifyWindow.setVisible(true);
            System.out.println(product_list_table.getSelectedRow());
            modifyWindow.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                updateList();
            }
        });
        }
        
    }//GEN-LAST:event_modify_product_buttonActionPerformed

    private void remove_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_buttonActionPerformed
        if (product_list_table.getSelectedRow() != -1 && !"none".equals(selectedItem)){
            Connection con = DBConnection.connect();
        
            try{
                DefaultTableModel table = (DefaultTableModel) product_list_table.getModel();
                Statement st = con.createStatement();
                
                String deleteQuery = "DELETE FROM product_list WHERE Name=\""+selectedItem+"\"";
                String rearrange1 = "SET @count = 0;";
                String rearrange2 = "UPDATE product_list SET product_list.ID = @count:= @count + 1;";
                String rearrange3 = "ALTER TABLE product_list AUTO_INCREMENT = 1;";
                
                st.executeUpdate(deleteQuery);
                st.executeUpdate(rearrange1);
                st.executeUpdate(rearrange2);
                st.executeUpdate(rearrange3);
                 
                con.close();
                   
                updateList();
            } catch (Exception a){
                System.out.println("Data not removed, ERROR: "  + a);
            }
        } else {
            //error
        }
    }//GEN-LAST:event_remove_buttonActionPerformed

    private void back_productlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_productlistActionPerformed
        new MainMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_productlistActionPerformed

    private void product_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_list_tableMouseClicked
        int row = product_list_table.getSelectedRow();
        selectedItem = (String) product_list_table.getValueAt(row, 1);
        System.out.println(selectedItem);
    }//GEN-LAST:event_product_list_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_productlist;
    private javax.swing.JButton create_new_product;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton modify_product_button;
    private javax.swing.JTable product_list_table;
    private javax.swing.JButton remove_button;
    // End of variables declaration//GEN-END:variables
}
